---
- hosts: elasticsearch
  become: yes
  gather_facts: no
  tasks: 
    - name: Install Python 
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: elasticsearch
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt keys
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: present 
    
    - name: Update Apt Repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
        state: present

    - name: Install relevant packages
      package: name={{item}} state=present
      with_items:
        - apt-transport-https
        - openjdk-8-jre
        - tmux
        - dstat
        - elasticsearch

    - name: Setup Elasticsearch configuration
      template:
        src: /root/elk_stack/roles/elasticsearch/templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
      notify: 
        - restart elasticsearch if configuration changed

  handlers: 
   - name: restart elasticsearch if configuration changed
     service: name=elasticsearch state=restarted






