---
 - hosts: localhost
   connection: local
   gather_facts: False
   vars:
       purpose: elasticsearch
   tasks:

     - name: Launch Instances (Type can be configured to match need)
       ec2:
         key_name: aws2-master
         instance_type: m3.large
         spot_price: .025
         spot_wait_timeout: 600
         image: ami-a58d0dc5
         wait: yes
         group: launch-wizard-1
         count: 3
         vpc_subnet_id: subnet-096fc340
         assign_public_ip: yes
         region: us-west-2
         instance_tags:
           type: "{{purpose}}"
       register: ec2_host

     - name: Globally register variable for later use (May not need this test later)
       set_fact: ec2_output={{ec2_host}}

     - name: Wait for SSH to become available
       wait_for:
         host: "{{ item.public_ip}}"
         port: 22
         delay: 10
         timeout: 320
         state: started
       with_items: "{{ ec2_host.instances }}"

     - name: Add dymanically created hosts to temporary inventory
       add_host:
         name: "{{ item.public_ip }}"
         groups: "{{purpose}}"
         ansible_ssh_private_key_file: '/root/aws2-master.pem'
         ansible_ssh_user: ubuntu
       with_items: "{{ ec2_host.instances }}"
